
package vehicalservicecenter;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class AppointmentDetails extends javax.swing.JFrame {

    DBConnection db = new DBConnection();
    PreparedStatement pst;
    ResultSet rs;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppointmentDetails.class.getName());

    public AppointmentDetails() {
        initComponents();
        tableLoad();
        customiseTable(appoTable);
        customiseButtons(btnUpdate, btnDelete);
        loadDigitalFont();
        setTime();

        UIManager.put("TextComponent.arc", 15);

        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblDateTime = new javax.swing.JLabel();
        lblDateTime1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appoTable = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtVNo = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRecord = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel6.setText("Time");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 60));

        lblDateTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDateTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblDateTime1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDateTime1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setText("A p p o i n t m e n t   D e t a i l s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 525, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateTime1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDateTime1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );

        panel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        table.setBackground(new java.awt.Color(255, 255, 255));

        appoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment ID", "Vehical No", "Date", "Time", "Status", "Record Date", "Who record"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(appoTable);
        if (appoTable.getColumnModel().getColumnCount() > 0) {
            appoTable.getColumnModel().getColumn(0).setResizable(false);
            appoTable.getColumnModel().getColumn(1).setResizable(false);
            appoTable.getColumnModel().getColumn(2).setResizable(false);
            appoTable.getColumnModel().getColumn(3).setResizable(false);
            appoTable.getColumnModel().getColumn(4).setResizable(false);
            appoTable.getColumnModel().getColumn(5).setResizable(false);
            appoTable.getColumnModel().getColumn(6).setResizable(false);
        }

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtVNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Appointment ID");

        jLabel3.setText("Vehical No");

        jLabel4.setText("Date");

        jLabel5.setText("Time");

        jLabel7.setText("Status");

        txtRecord.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("Recorded Date");

        javax.swing.GroupLayout tableLayout = new javax.swing.GroupLayout(table);
        table.setLayout(tableLayout);
        tableLayout.setHorizontalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tableLayout.createSequentialGroup()
                        .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        tableLayout.setVerticalGroup(
            tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3)
                .addGroup(tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtVNo)
                    .addComponent(txtDate)
                    .addComponent(txtTime)
                    .addComponent(txtStatus)
                    .addComponent(txtRecord))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        panel.add(table, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String keyword = txtSearch.getText().trim();
        searchAppointmentTable(keyword);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String appoId = txtId.getText().trim();

        if (appoId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an appointment from the table to delete!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to DELETE Appointment ID: " + appoId + "?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {

                String sql = "DELETE FROM appointment WHERE appo_id = ?";
                pst = db.con.prepareStatement(sql);
                pst.setString(1, appoId);

                int result = pst.executeUpdate();
                pst.close();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Appointment deleted successfully!");
                    searchAppointmentTable("");
                    clear();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Delete Error: " + ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String appoId = txtId.getText().trim();
        String newDate = txtDate.getText().trim();
        String newTime = txtTime.getText().trim();

        if (appoId.isEmpty() || newDate.isEmpty() || newTime.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an appointment and fill Date & Time!");
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to update this Appointment?", "Confirm Update", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {

                String sql = "UPDATE appointment SET date = ?, time = ? WHERE appo_id = ?";
                pst = db.con.prepareStatement(sql);
                pst.setString(1, newDate);
                pst.setString(2, newTime);
                pst.setString(3, appoId);

                int result = pst.executeUpdate();
                pst.close();

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Appointment updated successfully!");
                    searchAppointmentTable("");
                    clear();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Update Error: " + ex.getMessage());
            }
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void appoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appoTableMouseClicked
        int selectedRow = appoTable.getSelectedRow();

        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) appoTable.getModel();

            txtId.setText(model.getValueAt(selectedRow, 0).toString()); // Appointment ID
            txtVNo.setText(model.getValueAt(selectedRow, 1).toString()); // Vehical No
            txtStatus.setText(model.getValueAt(selectedRow, 4).toString()); // Status
            txtRecord.setText(model.getValueAt(selectedRow, 5).toString()); // Record Date
            txtDate.setText(model.getValueAt(selectedRow, 2).toString()); // Date (Editable)
            txtTime.setText(model.getValueAt(selectedRow, 3).toString()); // Time (Editable)

            txtId.setEditable(false);
            txtVNo.setEditable(false);
            txtStatus.setEditable(false);
            txtRecord.setEditable(false);

            txtDate.setEditable(true);
            txtTime.setEditable(true);

            txtDate.requestFocus();

            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);

            txtSearch.setText("");
        }
    }//GEN-LAST:event_appoTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
//            com.formdev.flatlaf.FlatDarkLaf.setup();

        } catch (Exception ex) {
            ex.printStackTrace();
            System.err.println("Failed to initialize LaF");
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentDetails().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appoTable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblDateTime1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel table;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtRecord;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtVNo;
    // End of variables declaration//GEN-END:variables

    private void tableLoad() {
        int c;
        try {
            pst = db.con.prepareStatement("SELECT * FROM appointment");
            rs = pst.executeQuery();

            ResultSetMetaData rd = rs.getMetaData();
            c = rd.getColumnCount();

            DefaultTableModel df = (DefaultTableModel) appoTable.getModel();

            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a <= c; a++) {
                    v2.add(rs.getString("appo_id"));
                    v2.add(rs.getString("vehical_no"));
                    v2.add(rs.getString("date"));
                    v2.add(rs.getString("time"));
                    v2.add(rs.getString("status"));
                    v2.add(rs.getString("recorded_at"));
                    v2.add(rs.getString("uName"));
                }
                df.addRow(v2);
            }
        } catch (SQLException ex) {

            Logger.getLogger(AppointmentDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchAppointmentTable(String keyword) {
        int c;
        try {
            DefaultTableModel model = (DefaultTableModel) appoTable.getModel();
            model.setRowCount(0);
            c = model.getColumnCount();

            String sql = "SELECT * FROM appointment WHERE vehical_no LIKE ? OR appo_id LIKE ? ORDER BY date DESC, time DESC";
            pst = db.con.prepareStatement(sql);
            pst.setString(1, "%" + keyword + "%");
            pst.setString(2, "%" + keyword + "%");

            rs = pst.executeQuery();

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a <= c; a++) {
                    v2.add(rs.getString("appo_id"));
                    v2.add(rs.getString("vehical_no"));
                    v2.add(rs.getString("date"));
                    v2.add(rs.getString("time"));
                    v2.add(rs.getString("status"));
                    v2.add(rs.getString("recorded_at"));
                    v2.add(rs.getString("uName"));

                }
                model.addRow(v2);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void customiseButtons(JButton btnUpdate, JButton btnDelete) {
        // Update Button - Green (Success)
        btnUpdate.setBackground(new Color(40, 167, 69));
        btnUpdate.setForeground(Color.WHITE);
//        btnUpdate.putClientProperty("JButton.buttonType", "roundRect");
        btnUpdate.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Delete Button - Red (Danger)
        btnDelete.setBackground(new Color(220, 53, 69));
        btnDelete.setForeground(Color.WHITE);
//        btnDelete.putClientProperty("JButton.buttonType", "roundRect");
        btnDelete.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    private void customiseTable(JTable table) {
        // 1. Header 
        table.getTableHeader().setFont(new Font("Segoe UI Semibold", Font.PLAIN, 14));
        table.getTableHeader().setBackground(new Color(43, 76, 126));
        table.getTableHeader().setForeground(Color.WHITE);
        table.getTableHeader().setPreferredSize(new Dimension(0, 30));
        table.getTableHeader().setBorder(BorderFactory.createEmptyBorder());

        // 2. Table 
        table.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        table.setRowHeight(40);
        table.setSelectionBackground(new Color(240, 245, 255));
        table.setSelectionForeground(new Color(0, 102, 204));

        // 3. Grid Lines 
        table.setShowGrid(false);
        table.setIntercellSpacing(new Dimension(0, 0));
        table.setGridColor(new Color(230, 230, 230));

        // 4. Matte Border 
        table.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(230, 230, 230)));

        // 5. Scroll Pane
        JScrollPane scrollPane = (JScrollPane) table.getParent().getParent();
        scrollPane.setBorder(BorderFactory.createEmptyBorder());
        scrollPane.getViewport().setBackground(Color.WHITE);

        // 6. Body 
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    private void loadDigitalFont() {
        try {
            InputStream is = getClass().getResourceAsStream("/file/Inter_18pt-SemiBold.ttf");
            Font digitalFont = Font.createFont(Font.TRUETYPE_FONT, is);

            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(digitalFont);

            lblDateTime.setFont(digitalFont.deriveFont(Font.PLAIN, 20f));
            lblDateTime1.setFont(digitalFont.deriveFont(Font.PLAIN, 15f));

        } catch (Exception e) {
            e.printStackTrace();
            lblDateTime.setFont(new Font("Consolas", Font.BOLD, 24));
        }
    }

    private void setTime() {
        new javax.swing.Timer(1000, e -> {
            // Digital font and 24-hour format (HH:mm:ss)
            String time = new java.text.SimpleDateFormat("HH:mm:ss a").format(new java.util.Date());
            String date = new java.text.SimpleDateFormat("EEE,MMM dd yyyy").format(new java.util.Date());
            lblDateTime.setText(date);
            lblDateTime1.setText(time);
            lblDateTime.setForeground(new java.awt.Color(4, 102, 200));
        }).start();
    }

    private void clear() {
        txtId.setText("");
        txtVNo.setText("");
        txtDate.setText("");
        txtTime.setText("");
        txtStatus.setText("");
        txtRecord.setText("");

        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }
}
