/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vehicalservicecenter;

import javax.swing.ImageIcon;

/**
 *
 * @author Damsith Dewmina
 */
public class DashBoard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashBoard.class.getName());

    ImageIcon img1 = new ImageIcon("C:\\Users\\Damsith Dewmina\\OneDrive\\Documents\\NetBeansProjects\\VehicalServiceCenter\\btns\\dashp.png");
    ImageIcon img2 = new ImageIcon("C:\\Users\\Damsith Dewmina\\OneDrive\\Documents\\NetBeansProjects\\VehicalServiceCenter\\btns\\stockp.png");

    public DashBoard() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        btnInventory = new javax.swing.JButton();
        btnDash = new javax.swing.JButton();
        btnTech = new javax.swing.JButton();
        btnStock2 = new javax.swing.JButton();
        btnStock3 = new javax.swing.JButton();
        btnStock4 = new javax.swing.JButton();
        pnlAll = new javax.swing.JPanel();
        pnlDash = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pnlStock = new javax.swing.JPanel();
        pnlAppoint = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pnlTech = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        main.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 170, 50));

        btnInventory.setBorder(null);
        btnInventory.addActionListener(this::btnInventoryActionPerformed);
        main.add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, 50));

        btnDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btns/light/Dash.png"))); // NOI18N
        btnDash.setBorder(null);
        btnDash.addActionListener(this::btnDashActionPerformed);
        main.add(btnDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 50));

        btnTech.setBorder(null);
        btnTech.addActionListener(this::btnTechActionPerformed);
        main.add(btnTech, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 170, 50));

        btnStock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btns/light/Appoint.png"))); // NOI18N
        btnStock2.setBorder(null);
        btnStock2.addActionListener(this::btnStock2ActionPerformed);
        main.add(btnStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 50));

        btnStock3.setBorder(null);
        btnStock3.addActionListener(this::btnStock3ActionPerformed);
        main.add(btnStock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 170, 50));

        btnStock4.setBorder(null);
        btnStock4.addActionListener(this::btnStock4ActionPerformed);
        main.add(btnStock4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 170, 50));

        pnlAll.setBackground(new java.awt.Color(255, 255, 255));
        pnlAll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        pnlDash.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 507, 900, 290));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Dash.png"))); // NOI18N
        pnlDash.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 830));

        pnlAll.add(pnlDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout pnlStockLayout = new javax.swing.GroupLayout(pnlStock);
        pnlStock.setLayout(pnlStockLayout);
        pnlStockLayout.setHorizontalGroup(
            pnlStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        pnlStockLayout.setVerticalGroup(
            pnlStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );

        pnlAll.add(pnlStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlAppoint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(jTable2);

        pnlAppoint.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 667, 900, 120));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Appoint.png"))); // NOI18N
        pnlAppoint.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 830));

        pnlAll.add(pnlAppoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlTech.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setMaximumSize(new java.awt.Dimension(990, 830));
        jLabel4.setMinimumSize(new java.awt.Dimension(990, 830));
        jLabel4.setPreferredSize(new java.awt.Dimension(990, 830));
        pnlTech.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 830));

        pnlAll.add(pnlTech, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 830));

        main.add(pnlAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 990, 830));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Alll.png"))); // NOI18N
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 920));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        lblname.setIcon(img1);
//        pnlAll.setVisible(true);
        pnlDash.setVisible(true);

    }//GEN-LAST:event_formWindowOpened

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
//        lblname.setIcon(img2);
        pnlDash.setVisible(false);
        pnlStock.setVisible(true);
        pnlAppoint.setVisible(false);
        pnlTech.setVisible(false);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashActionPerformed
//        lblname.setIcon(img1);
        pnlDash.setVisible(true);
        pnlStock.setVisible(false);
        pnlAppoint.setVisible(false);
        pnlTech.setVisible(false);
    }//GEN-LAST:event_btnDashActionPerformed

    private void btnTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechActionPerformed
//        lblname.setIcon(img1);
        pnlDash.setVisible(false);
        pnlStock.setVisible(false);
        pnlAppoint.setVisible(false);
        pnlTech.setVisible(true);

    }//GEN-LAST:event_btnTechActionPerformed

    private void btnStock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStock2ActionPerformed
        pnlAppoint.setVisible(true);
        pnlDash.setVisible(false);
        pnlStock.setVisible(false);
        pnlTech.setVisible(false);
    }//GEN-LAST:event_btnStock2ActionPerformed

    private void btnStock3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStock3ActionPerformed

        Register reg = new Register();
        reg.setVisible(true);
    }//GEN-LAST:event_btnStock3ActionPerformed

    private void btnStock4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStock4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStock4ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashBoard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDash;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnStock2;
    private javax.swing.JButton btnStock3;
    private javax.swing.JButton btnStock4;
    private javax.swing.JButton btnTech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblname;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlAppoint;
    private javax.swing.JPanel pnlDash;
    private javax.swing.JPanel pnlStock;
    private javax.swing.JPanel pnlTech;
    // End of variables declaration//GEN-END:variables
}
